STILE_SRCS =	../stile/Stile.cc \
	../stile/core/Configurator.cc \
	../stile/core/ConfiguratorInit.cc \
	../stile/core/EventManager.cc \
	../stile/core/EventManagerInit.cc \
	../stile/core/Init.cc \
	../stile/core/Initiator.cc \
	../stile/core/Logger.cc \
	../stile/core/LoggerInit.cc \
	../stile/core/Timer.cc \
	../stile/core/TimerInit.cc \
	../stile/core/Entity.cc \
	../stile/core/World.cc \
	../stile/core/Engine.cc \
	../stile/math/Vectors.cc

STILE_OBJS =	Stile.o \
	Configurator.o \
	ConfiguratorInit.o \
	EventManager.o \
	EventManagerInit.o \
	Init.o \
	Initiator.o \
	Logger.o \
	LoggerInit.o \
	Timer.o \
	TimerInit.o \
	Entity.o \
	World.o \
	Engine.o \
	Vectors.o

